### ISSUE TITLE
Nefunguje odkaz na AWS DNS migraci

### ISSUE THREAD

**Issue by messa** [pyvec/docs.pyvec.org#110]
https://docs.pyvec.org/operations/domains.html

"DNS je stále na AWS Tomáše Ehrlicha, návod jak to zmigrovat je zde."

míří to na 404: https://docs.pyvec.org/operations/aws-dns

Niméně kdyby bylo potřeba, tak s AWS můžu pomoct.

**Comment by honzajavorek** [comment]
Díky, to mělo vést sem: https://pyvec.slack.com/archives/C6ZMKC50E/p1574335038001900

**Comment by honzajavorek** [comment]
Koukám, že je to tam, ale je potřeba udělat nějaký čoromoro s reST markupem. Chtěl jsem ten link mít pod tabulkou, aby nezabíral moc místa, ale propojení se někde ztrácí v překladu.
