### ISSUE TITLE
Zdokumentovat kdo má přístup na Roští

### ISSUE THREAD

**Issue by encukou** [pyvec/docs.pyvec.org#288]
Pyvec má účet u Roští. Jede tam pyvo.cz, python.cz (?!), stránky PyConu a nový zpětnovazebník.
Já tam mám přístup a rád něco poměním, ale nevím kdo další má přístupy. Stálo by za to to zdokumentovat.

@honzajavorek, máš víc informací?

**Comment by honzajavorek** [comment]
Koukám, že já se tam přihlašuju přes osobní účet. Pak vidím tohle:

<img width="878" alt="Screenshot 2022-09-16 at 13 29 24" src="https://user-images.githubusercontent.com/283441/190629261-1681a393-3a57-4ab2-9d11-63924139ded5.png">

Pak můžu dát spravovat firmu a tam vidím tohle:

<img width="1218" alt="Screenshot 2022-09-16 at 13 30 26" src="https://user-images.githubusercontent.com/283441/190629595-5e3bb9bf-fb25-4428-8ff5-f5672f882cfa.png">

**Comment by honzajavorek** [comment]
To znamená já, @encukou, @starenka, @messa, @aleszoulek

**Comment by encukou** [comment]
Díky! A když se někdo bude chtít připojit, má asi požadat board, že?

**Comment by honzajavorek** [comment]
Asi jo. Ale hlavně by tam teda měl mít přístup nějak board a ne jenom já :)
