### ISSUE TITLE
Destroy the "documents" repo

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/docs.pyvec.org#67]
Move docs from https://github.com/pyvec/documents here or to our Google Drive and delete the repository

**Comment by honzajavorek** [comment]
There are three documents:

- [x] Pracuj pro Python (idea v2015) by me - I copied the text to https://docs.google.com/document/d/1Kb-JYvqPTftEkZupnVJNgjBP5TlQhrJKc_MPIo7Dudk/edit#heading=h.hbpbv2hyd660 for archivation purposes and the document can be deleted
- [x] charter (bylaws) of the old Pyvec by @encukou - I think we can delete that, we have https://docs.pyvec.org/operations/bylaws.html now
- [ ] CoC by @encukou and @Luminaar - not sure whether this is still used or linked from anywhere... any ideas? the last update was 3 years ago and the conference includes CoC on their site https://cz.pycon.org/2019/coc/ I guess we can delete that document as well?

If we can delete all three, I think I'll just remove the repo (yes, remove, as I don't think archivation of the repo has any benefit here).

**Comment by Luminaar** [comment]
I think it is OK to remove the CoC. Since it's explicitly named `conference-coc`, it can live in the website repo.

**Comment by encukou** [comment]
> If we can delete all three, I think I'll just remove the repo (yes, remove, as I don't think archivation of the repo has any benefit here).

Please archive it, so external links continue to work.

**Comment by honzajavorek** [comment]
Do you know about any? I have experienced people reading and contacting me
about content in archived repos, ignoring the warning. In case of documents
like bylaws, I’d like to avoid that. Clear 404 is communicating that people
need to find the content elsewhere.

I could edit all documents and replace their content with links to
alternatives, but that just seems like unnecessary work if the repo is dead
enough.

**Comment by encukou** [comment]
> Do you know about any? 

I don't, off the top of my head – if I did I'd change them. But I also know many external links the target doesn't know about.
