### ISSUE TITLE
Zdokumentovat stav domén

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/docs.pyvec.org#96]
Momentálně je stav v živoucím příspěvku zde: https://pyvec.slack.com/archives/C6ZMKC50E/p1511814144000177

Bylo by lepší ho mít tady? Nebo si ten příspěvek sosnout přes API a zobrazovat to i tady? Nebo tady dát aspoň jen odkaz na ten příspěvek do https://docs.pyvec.org/operations/support.html#domeny ?

**Comment by encukou** [comment]
Myslím že by to bylo lepší mít tady. Slack je dělaný na rychlou komunikaci, ne na dokumenty.

**Comment by honzajavorek** [comment]
Taky prave mám ten pocit. Dřív bylo dobry to mít rychle editovatelné, ale
teď už se to tolik nemění a editace přes PR by stačila.
